config/routes.rb
Rails4::Application.routes.draw do
  resources :memos

  get "home/index"
  get "home/practice_link"

end

app/models/memo.rb
class Memo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: 'Memo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @memo }
      else
        format.html { render action: 'new' }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memo_params
      params.require(:memo).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def practice_link
    logger.debug "saaaa"
    
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.erb
=link_to practice_link, 'practice_link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rails4
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

app/views/memos/_form.html.haml
= form_for @memo do |f|
  - if @memo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@memo.errors.count, "error")} prohibited this memo from being saved:"
      %ul
        - @memo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/memos/edit.html.haml
%h1 Editing memo

= render 'form'

= link_to 'Show', @memo
\|
= link_to 'Back', memos_path

app/views/memos/index.html.haml
%h1 Listing memos

%table
  %tr
    %th Title
    %th Body
    %th
    %th
    %th

  - @memos.each do |memo|
    %tr
      %td= memo.title
      %td= memo.body
      %td= link_to 'Show', memo
      %td= link_to 'Edit', edit_memo_path(memo)
      %td= link_to 'Destroy', memo, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Memo', new_memo_path

app/views/memos/new.html.haml
%h1 New memo

= render 'form'

= link_to 'Back', memos_path

app/views/memos/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @memo.title
%p
  %b Body:
  = @memo.body

= link_to 'Edit', edit_memo_path(@memo)
\|
= link_to 'Back', memos_path